//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeptuneDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int DeviceId { get; set; }
        public string Device1 { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Note1 { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    }
}
